# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
zh:
  languageCode: zh-Hans
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en en-us

# Uncomment the lines below to configure your website in a second language.
en:
  languageCode: en-us
  contentDir: content/en
  title: Hao Xu
  params:
    description: Hao Xu
  menu:
    main:
      - name: Home
        url: '#about'
        weight: 10
      - name: Publication
        url: '#publications'
        weight: 20
      - name: Post
        url: '#posts'
        weight: 30
      - name: Project
        url: '#projects'
        weight: 40     
      - name: Contact
        url: '#contact'
        weight: 60
